postgres:
  imports:
    - lib/pq
    - jackc/pgx
  code_patterns:
    - sql.Open
  image: postgres:16-alpine
  port: "5432"

mysql:
  imports:
    - go-sql-driver/mysql
  code_patterns:
    - sql.Open
  image: mysql:8
  port: "3306"

redis:
  imports:
    - go-redis/redis
    - redis/go-redis
  code_patterns:
    - redis.NewClient
  image: redis:alpine
  port: "6379"

mongo:
  imports:
    - mongo-driver
  code_patterns:
    - mongo.Connect
  image: mongo:7
  port: "27017"

elasticsearch:
  imports:
    - elastic/go-elasticsearch
    - olivere/elastic
  code_patterns: []
  image: elasticsearch:8.12.0
  port: "9200"

rabbitmq:
  imports:
    - rabbitmq/amqp091-go
    - streadway/amqp
  code_patterns:
    - amqp.Dial
  image: rabbitmq:3-management-alpine
  port: "5672"

kafka:
  imports:
    - segmentio/kafka-go
    - confluentinc/confluent-kafka
  code_patterns: []
  image: bitnami/kafka:latest
  port: "9092"

nats:
  imports:
    - nats-io/nats.go
  code_patterns:
    - nats.Connect
  image: nats:alpine
  port: "4222"

memcached:
  imports:
    - bradfitz/gomemcache
  code_patterns: []
  image: memcached:alpine
  port: "11211"

minio:
  imports:
    - minio/minio-go
  code_patterns: []
  image: minio/minio:latest
  port: "9000"

influxdb:
  imports:
    - influxdata/influxdb-client-go
  code_patterns: []
  image: influxdb:2-alpine
  port: "8086"

cassandra:
  imports:
    - gocql/gocql
  code_patterns: []
  image: cassandra:4
  port: "9042"

clickhouse:
  imports:
    - ClickHouse/clickhouse-go
    - mailru/go-clickhouse
  code_patterns: []
  image: clickhouse/clickhouse-server:latest
  port: "9000"

neo4j:
  imports:
    - neo4j/neo4j-go-driver
  code_patterns: []
  image: neo4j:5
  port: "7687"

couchbase:
  imports:
    - couchbase/gocb
  code_patterns: []
  image: couchbase:community-7.2.0
  port: "8091"

etcd:
  imports:
    - etcd-io/etcd/client
  code_patterns: []
  image: bitnami/etcd:latest
  port: "2379"

consul:
  imports:
    - hashicorp/consul/api
  code_patterns: []
  image: hashicorp/consul:latest
  port: "8500"

vault:
  imports:
    - hashicorp/vault/api
  code_patterns: []
  image: hashicorp/vault:latest
  port: "8200"

jaeger:
  imports:
    - jaegertracing/jaeger-client-go
  code_patterns: []
  image: jaegertracing/all-in-one:latest
  port: "16686"

zipkin:
  imports:
    - openzipkin/zipkin-go
  code_patterns: []
  image: openzipkin/zipkin:latest
  port: "9411"

cockroachdb:
  imports:
    - cockroachdb/cockroach-go
  code_patterns: []
  image: cockroachdb/cockroach:latest
  port: "26257"

dgraph:
  imports:
    - dgraph-io/dgo
  code_patterns: []
  image: dgraph/standalone:latest
  port: "8080"

arangodb:
  imports:
    - arangodb/go-driver
  code_patterns: []
  image: arangodb:latest
  port: "8529"

scylladb:
  imports:
    - scylladb/gocqlx
  code_patterns: []
  image: scylladb/scylla:latest
  port: "9042"

opensearch:
  imports:
    - opensearch-project/opensearch-go
  code_patterns: []
  image: opensearchproject/opensearch:latest
  port: "9200"

prometheus:
  imports:
    - prometheus/client_golang
  code_patterns: []
  image: prom/prometheus:latest
  port: "9090"
